version: '3'
services:
    db:
        image: mysql/mysql-server:5.7
        container_name: laravel-db
        networks:
            - laravel-network
        #        volumes:
        #            - /db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        expose:
            - "3306"
        ports:
            - "3306:3306"
    app:
        build:
            context: .
            args:
                MODE: 'development'
        image: laravel:latest
        container_name: laravel-app
        networks:
            - laravel-network
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        restart: always
        ports:
            - "8080:80"
        environment:
          DB_HOST: db
networks:
    laravel-network:
